apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-service
  template:
    metadata:
      labels:
        app: etl-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - etl-ingest
      containers:
      - name: etl-service
        image: etl-service:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: etl-service
spec:
  selector:
    app: etl-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
