apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ml-log
      containers:
      - name: log-service
        image: log-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: log-service
  type: NodePort           # Expose service outside the cluster
  ports:
    - protocol: TCP
      port: 8001           # Cluster port
      targetPort: 8001     # Pod port
      nodePort: 30011      # External port on Minikube node
